linters:
  StringQuotes:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
  NestingDepth:
    enabled: true
    ignore_parent_selectors: true
  HexLength:
    enabled: false
  UrlQuotes:
    enabled: false